---

- name: Increase max number of file descriptors
  copy:
    src: etc/security/limits.conf
    dest: /etc/security/limits.conf

- name: Optimizing network kernel parameters
  copy:
    src: etc/sysctl.conf
    dest: /etc/sysctl.conf

- name: Reload Sysctl
  command: /bin/true
  notify:
    - reload sysctl.conf

- name: Install td-agent
  shell: curl -L https://toolbelt.treasuredata.com/sh/install-debian-stretch-td-agent3.sh | sh
  notify:
    - reload td-agent
