---

- name: Increase max number of file descriptors
  copy:
    src: etc/security/limits.conf
    dest: /etc/security/limits.conf

- name: Optimizing network kernel parameters
  copy:
    src: etc/sysctl.conf
    dest: /etc/sysctl.conf

- name: Reload Sysctl
  command: /bin/true
  notify:
    - reload sysctl.conf
